[project]
name = "client-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.41.0",
    "mcp>=1.21.2",
]
